# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1356074695);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1356074815);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1356078055);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1356074575);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.migration.version", 7);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.showQuitWarning", true);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.warnOnQuit", false);
user_pref("devtools.errorconsole.enabled", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountTotal", 7);
user_pref("extensions.blocklist.pingCountVersion", 7);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-QC86UtwBdeULQw@jetpack\":{\"version\":\"0.1\",\"type\":\"extension\",\"descriptor\":\"/home/ivan/workspace/ffscrap/test-profile/extensions/jid1-QC86UtwBdeULQw@jetpack.xpi\"}}");
user_pref("extensions.checkCompatibility.17.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "mint-search-enhancer%40linuxmint.com:1.0,langpack-en-GB%40firefox.mozilla.org:17.0.1,langpack-en-ZA%40firefox.mozilla.org:17.0.1,%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D:1.0.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.1");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"mint-search-enhancer@linuxmint.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/mint-search-enhancer@linuxmint.com\",\"mtime\":1336764747000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1355289720000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1354213882000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1354213882000},\"{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\",\"mtime\":1336783780000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-QC86UtwBdeULQw@jetpack\":{\"descriptor\":\"/home/ivan/workspace/ffscrap/test-profile/extensions/jid1-QC86UtwBdeULQw@jetpack.xpi\",\"mtime\":1356083137000}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.jid1-QC86UtwBdeULQw@jetpack.scrapperSource", "http://localhost/scrappers.json");
user_pref("extensions.lastAppVersion", "17.0.1");
user_pref("extensions.lastPlatformVersion", "17.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.testpilot.runStudies", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("idle.lastDailyNotification", 1355951881);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("javascript.options.strict", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1355566700);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1355566700);
user_pref("toolkit.startup.last_success", 1356083137);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1358154847);
user_pref("urlclassifier.updateinterval", 172800);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
